name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Update Script
        run: |
          echo "## Dynamic Section" > dynamic_content.txt
          echo "Last updated: $(date)" >> dynamic_content.txt
          cat dynamic_content.txt
          mv dynamic_content.txt README.md

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GH_TOKEN: $GH_TOKEN"  # Ensure this line is commented out in actual use to avoid printing secrets

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Automated update of README.md'
          git remote set-url origin https://$GH_TOKEN@github.com/${{ github.repository }}.git
          git push origin HEAD:main

